# Credit: https://github.com/marketplace/actions/count-lines-of-code-cloc
name: Count Lines of Code

on: [push, pull_request]

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CLOC action
        uses: djdefi/cloc-action@v1 # Use the chosen CLOC action
        with:
          args: "--md --report-file=cloc_report.md" # Customize CLOC arguments
          
      - name: Upload CLOC report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloc-report
          path: cloc_report.md
